name: Generator

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate-emoji-table:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python generator.py > emoji-table.txt
      - name: concat files
        run: cat romantable-orig.txt emoji-table.txt > romantable.txt
      - name: release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            romantable.txt
